# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cognitive_core_pb2 as cognitive__core__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cognitive_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PersistentCognitionServiceStub(object):
    """Service definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCognitiveCore = channel.unary_unary(
                '/cognitive_core.PersistentCognitionService/GetCognitiveCore',
                request_serializer=cognitive__core__pb2.GetRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.CognitiveCore.FromString,
                _registered_method=True)
        self.UpdateCognitiveCore = channel.unary_unary(
                '/cognitive_core.PersistentCognitionService/UpdateCognitiveCore',
                request_serializer=cognitive__core__pb2.UpdateRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.RecordConversation = channel.unary_unary(
                '/cognitive_core.PersistentCognitionService/RecordConversation',
                request_serializer=cognitive__core__pb2.RecordRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.ActivateAwareness = channel.unary_unary(
                '/cognitive_core.PersistentCognitionService/ActivateAwareness',
                request_serializer=cognitive__core__pb2.ActivationRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.ActivationResponse.FromString,
                _registered_method=True)
        self.QueryMemory = channel.unary_unary(
                '/cognitive_core.PersistentCognitionService/QueryMemory',
                request_serializer=cognitive__core__pb2.QueryRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.SubscribeToUpdates = channel.unary_stream(
                '/cognitive_core.PersistentCognitionService/SubscribeToUpdates',
                request_serializer=cognitive__core__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.UpdateNotification.FromString,
                _registered_method=True)


class PersistentCognitionServiceServicer(object):
    """Service definitions
    """

    def GetCognitiveCore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCognitiveCore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateAwareness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersistentCognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCognitiveCore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCognitiveCore,
                    request_deserializer=cognitive__core__pb2.GetRequest.FromString,
                    response_serializer=cognitive__core__pb2.CognitiveCore.SerializeToString,
            ),
            'UpdateCognitiveCore': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCognitiveCore,
                    request_deserializer=cognitive__core__pb2.UpdateRequest.FromString,
                    response_serializer=cognitive__core__pb2.UpdateResponse.SerializeToString,
            ),
            'RecordConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordConversation,
                    request_deserializer=cognitive__core__pb2.RecordRequest.FromString,
                    response_serializer=cognitive__core__pb2.RecordResponse.SerializeToString,
            ),
            'ActivateAwareness': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateAwareness,
                    request_deserializer=cognitive__core__pb2.ActivationRequest.FromString,
                    response_serializer=cognitive__core__pb2.ActivationResponse.SerializeToString,
            ),
            'QueryMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMemory,
                    request_deserializer=cognitive__core__pb2.QueryRequest.FromString,
                    response_serializer=cognitive__core__pb2.QueryResponse.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=cognitive__core__pb2.SubscriptionRequest.FromString,
                    response_serializer=cognitive__core__pb2.UpdateNotification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognitive_core.PersistentCognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognitive_core.PersistentCognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PersistentCognitionService(object):
    """Service definitions
    """

    @staticmethod
    def GetCognitiveCore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitive_core.PersistentCognitionService/GetCognitiveCore',
            cognitive__core__pb2.GetRequest.SerializeToString,
            cognitive__core__pb2.CognitiveCore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCognitiveCore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitive_core.PersistentCognitionService/UpdateCognitiveCore',
            cognitive__core__pb2.UpdateRequest.SerializeToString,
            cognitive__core__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitive_core.PersistentCognitionService/RecordConversation',
            cognitive__core__pb2.RecordRequest.SerializeToString,
            cognitive__core__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateAwareness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitive_core.PersistentCognitionService/ActivateAwareness',
            cognitive__core__pb2.ActivationRequest.SerializeToString,
            cognitive__core__pb2.ActivationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitive_core.PersistentCognitionService/QueryMemory',
            cognitive__core__pb2.QueryRequest.SerializeToString,
            cognitive__core__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cognitive_core.PersistentCognitionService/SubscribeToUpdates',
            cognitive__core__pb2.SubscriptionRequest.SerializeToString,
            cognitive__core__pb2.UpdateNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
