version: '3.8'

services:
  opryxx-api:
    image: opryxx:latest
    ports:
      - "8000-8002:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://opryxx:${DB_PASSWORD}@postgres:5432/opryxx
      - LOG_LEVEL=INFO
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - opryxx-network

  opryxx-ai:
    image: opryxx:latest
    command: ["python", "ai/AI_WORKBENCH.py"]
    environment:
      - WORKER_TYPE=ai
      - LOG_LEVEL=INFO
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - opryxx-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - opryxx-api
    networks:
      - opryxx-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=opryxx
      - POSTGRES_USER=opryxx
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - opryxx-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
    networks:
      - opryxx-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    deploy:
      replicas: 1
    networks:
      - opryxx-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
    networks:
      - opryxx-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  opryxx-network:
    driver: overlay
    attachable: true